language: android
jdk: oraclejdk7
env:
  global:
    - COVERALLS_REPO_TOKEN=4CR398SQOtypPILwF7fgKUjG3LYy15i3D
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

before_install:
 - chmod +x gradlew

script: ./gradlew jacocoTestReport coveralls